# sh scripts/SAPMixer/etth1.sh;
# sh scripts/SAPMixer/etth2.sh;
# sh scripts/SAPMixer/ettm1.sh;
# sh scripts/SAPMixer/ettm2.sh;
# sh scripts/SAPMixer/weather.sh;
# sh scripts/SAPMixer/electricity.sh;
# sh scripts/SAPMixer/traffic.sh;
sh scripts/SAPMixer/pems03.sh;
sh scripts/SAPMixer/pems04.sh;
sh scripts/SAPMixer/pems07.sh;
sh scripts/SAPMixer/pems08.sh;